version: "3.9"

services:
  app:
    build: ./app
    restart: unless-stopped
    volumes:
      - .:/home/dev/src:cached
      - icc_dumps:/home/dev/icc_dumps:ro
    environment:
      - APP_FACTORY=app:create_app
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
    ports:
      - 5000:5000

volumes:
  icc_dumps:
    external: true
