version: "3.9"

services:
  app:
    build: ./app
    command: /bin/sh -c "while sleep 1000; do :; done"
    restart: unless-stopped
    volumes:
      - .:/home/dev/src:cached
      - icc_git_input:/home/dev/icc_git_input:ro
    environment:
      - FLASK_APP=/home/dev/src/app/app
      - FLASK_RUN_PORT=5000

volumes:
  icc_git_input:
    external: true
