version: "3.9"

services:
  app:
    build:
      args:
        - APP_PORT=5000
      context: .
      target: production
    user: foxconnect
    restart: unless-stopped
    volumes:
      - icc_dumps:/fc/icc_dumps:ro
    ports:
      - 5000:5000

volumes:
  icc_dumps:
    external: true
