version: "3.9"

services:
  app:
    build: ./app
    restart: unless-stopped
    volumes:
      - .:/home/dev/src:cached
      - icc_git_input:/home/dev/icc_git_input:ro
    environment:
      - APP_OBJECT=app:create_app
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
    ports:
      - "5000:5000"

volumes:
  icc_git_input:
    external: true
