services:
  app:
    build:
      args:
        - APP_PORT=5000
      context: .
      target: production
    user: foxconnect
    restart: on-failure:3
    init: true
    volumes:
      - icc_dumps:/home/foxconnect/icc_dumps:ro
    ports:
      - 5000:5000

volumes:
  icc_dumps:
    external: true
