[tool.uv]
dev-dependencies = ["setuptools"]

[tool.uv.sources]
app = { workspace = true }
foxdata = { workspace = true }
pyd3graphviz = { workspace = true }
pyfastmurmur3 = { workspace = true }
pyhtmx = { workspace = true }
utils = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
line-length = 120
namespace-packages = ["packages/utils/src"]
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.per-file-ignores]
"setup.py" = ["INP001"]

[tool.ruff.lint]
ignore = ["ANN401", "B023", "PYI021", "PYI048", "RET505"]

extend-select = [
    "E",
    "W",
    "N",
    "ANN",
    "C90",
    "UP",
    "ASYNC",
    "S",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "FA",
    "ISC",
    "ICN",
    "INP",
    "PYI",
    "Q",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TC",
    "INT",
    "PL",
    "FLY",
    "PERF",
    "RUF",
]
