[package]
name = "pyfastmurmur3"
version = "0.2.3"
edition = "2021"

[lib]
name = "fastmurmur3"
crate-type = ["cdylib"]

[dependencies]
fastmurmur3 = "0.2.0"
pyo3 = { version = "0.25.1", features = ["extension-module"] }

[profile.dev]
lto = "off"
opt-level = 0

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
