INITIAL_SEED = 100001
MAX_STACK_LENGTH = 16

CONDITIONAL_BRANCHES = ("BIF", "BII", "BIN", "BIP", "BIT", "BIZ")
UNCONDITIONAL_BRANCHES = ("GTO",)
TERMINATION_INSTRUCTIONS = ("END", "EXIT")
BREAKING_INSTRUCTIONS = ("GTI",)

BRANCH_INSTRUCTIONS = (
    *CONDITIONAL_BRANCHES,
    *UNCONDITIONAL_BRANCHES,
)

SPECIAL_INSTRUCTIONS = (
    "START",
    *CONDITIONAL_BRANCHES,
    *UNCONDITIONAL_BRANCHES,
    *TERMINATION_INSTRUCTIONS,
    *BREAKING_INSTRUCTIONS,
)

END_STEP_NUMBER = 51
