version: "3.9"

services:
  app-dev:
    build:
      args:
        - APP_PORT=5001
      context: ../app
      target: dev
    restart: unless-stopped
    volumes:
      - ..:/foxconnect/src
      - icc_dumps:/foxconnect/icc_dumps:ro
    ports:
      - 5001:5001

volumes:
  icc_dumps:
    external: true
