version: "3.9"

services:
  app-dev:
    build:
      args:
        - APP_PORT=5001
      context: ..
      target: dev
    user: foxconnect
    restart: unless-stopped
    volumes:
      - ..:/fc/repo
      - icc_dumps:/fc/icc_dumps:ro
    ports:
      - 5001:5001

volumes:
  icc_dumps:
    external: true
