[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quart_foxdata"
version = "0.0.1"
dependencies = [
    "pyfastmurmur3",
    "Quart",
    "billiard",
]
